export type OutlineItem = {
  displayText: string;
  id: string;
  level: "h2" | "h3" | "h4";
  contentSource?: "authored" | "handbook";
  sourceTag?: "p7" | "li7" | "li27";
  sourceText?: string;
  showInMenu?: boolean;
};

export const questionnaireDesignOutline: OutlineItem[] = [
  {
    displayText: "Questionnaire foundations",
    id: "introduction",
    level: "h2",
    sourceTag: "p7",
    sourceText: "Introduction",
    showInMenu: true,
  },
  {
    displayText: "Useful websites",
    id: "useful-web-sites",
    level: "h2",
    sourceTag: "p7",
    sourceText: "Some useful web sites",
    showInMenu: true,
  },
  {
    displayText: "The quantitative social survey method",
    id: "the-quantitative-social-survey-method",
    level: "h2",
    sourceTag: "p7",
    sourceText: "1 THE quantitative SOCIAL survey METHOD",
    showInMenu: true,
  },
  {
    displayText: "Measurement error in survey research",
    id: "measurement-error-in-survey-research",
    level: "h2",
    sourceTag: "p7",
    sourceText: "2 measurement and error in survey research",
    showInMenu: true,
  },
  {
    displayText: "Choosing the method of data collection",
    id: "choosing-the-method-of-data-collection",
    level: "h2",
    sourceTag: "p7",
    sourceText: "3 Choosing the method of data collection",
    showInMenu: true,
  },
  {
    displayText: "Identifying the variables for survey research",
    id: "identifying-the-variables-for-survey-research",
    level: "h2",
    sourceTag: "li27",
    sourceText: "4 Identifying the variables for survey research",
    showInMenu: true,
  },
  {
    displayText: "Approaches to determining questionnaire content",
    id: "approaches-to-determining-questionnaire-content",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Approaches to determining questionnaire content",
    showInMenu: true,
  },
  {
    displayText: "Determining the variables to be included",
    id: "determining-the-variables-to-be-included",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Determining the variables to be included",
    showInMenu: true,
  },
  {
    displayText: "Defining variables",
    id: "defining-variables",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Defining variables",
    showInMenu: true,
  },
  {
    displayText: "Types of data",
    id: "types-of-data",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Types of data",
    showInMenu: true,
  },
  {
    displayText: "Choosing a suitable scale of measurement",
    id: "choosing-a-suitable-scale-of-measurement",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Choosing a suitable scale of measurement",
    showInMenu: true,
  },
  {
    displayText: "Sources of survey questions",
    id: "sources-of-survey-questions",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Sources of survey questions",
    showInMenu: true,
  },
  {
    displayText: "The UK Data Service",
    id: "the-uk-data-service",
    level: "h4",
    sourceTag: "p7",
    sourceText: "The UK Data Service",
    showInMenu: true,
  },
  {
    displayText: "ONS harmonised questions",
    id: "ons-harmonised-questions",
    level: "h4",
    sourceTag: "p7",
    sourceText: "ONS harmonised questions",
    showInMenu: true,
  },
  {
    displayText: "Questions from US polls and surveys",
    id: "questions-from-us-polls-and-surveys",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Questions from US polls and surveys",
    showInMenu: true,
  },
  {
    displayText: "Core outcomes",
    id: "core-outcomes",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Core outcomes",
    showInMenu: true,
  },
  {
    displayText: "Questions on health status and quality of life",
    id: "questions-on-health-status-and-quality-of-life",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Questions on health status and quality of life",
    showInMenu: true,
  },
  {
    displayText: "Questions on patient satisfaction",
    id: "questions-on-patient-satisfaction",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Questions on patient satisfaction",
    showInMenu: true,
  },
  {
    displayText: "Devising survey questions",
    id: "devising-survey-questions",
    level: "h2",
    sourceTag: "p7",
    sourceText: "5 Devising survey questions",
    showInMenu: true,
  },
  {
    displayText: "Communicative and scientific aims of quantitative surveys",
    id: "communicative-and-scientific-aims-of-quantitative-surveys",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Communicative and scientific aims of quantitative surveys",
    showInMenu: true,
  },
  {
    displayText: "Cognitive aspects of survey methodology",
    id: "cognitive-aspects-of-survey-methodology",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Cognitive aspects of survey methodology",
    showInMenu: true,
  },
  {
    displayText: "Asking about behaviour",
    id: "asking-about-behaviour",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Asking about behaviour",
    showInMenu: true,
  },
  {
    displayText: "Distortions of recall and reporting of events and behaviour",
    id: "distortions-of-recall-and-reporting-of-events-and-behaviour",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Distortions of recall and reporting of events and behaviour",
    showInMenu: true,
  },
  {
    displayText: "Forgetting",
    id: "forgetting",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Forgetting",
    showInMenu: true,
  },
  {
    displayText: "Deliberate omissions and distortions",
    id: "deliberate-omissions-and-distortions",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Deliberate omissions and distortions",
    showInMenu: true,
  },
  {
    displayText: "Unconscious omissions and distortions",
    id: "unconscious-omissions-and-distortions",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Unconscious omissions and distortions",
    showInMenu: true,
  },
  {
    displayText: "Rationalisation",
    id: "rationalisation",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Rationalisation",
    showInMenu: true,
  },
  {
    displayText: "Distortion of the perception of elapsed time",
    id: "distortion-of-the-perception-of-elapsed-time",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Distortion of the perception of elapsed time",
    showInMenu: true,
  },
  {
    displayText: "Challenges of posing questions about behaviour and events",
    id: "challenges-of-posing-questions-about-behaviour-and-events",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Challenges of posing questions about behaviour and events",
    showInMenu: true,
  },
  {
    displayText: "The form and wording of questions to measure behaviour",
    id: "the-form-and-wording-of-questions-to-measure-behaviour",
    level: "h4",
    sourceTag: "p7",
    sourceText: "The form and wording of questions to measure behaviour",
    showInMenu: true,
  },
  {
    displayText: "Enhancing accuracy and completeness of response",
    id: "enhancing-accuracy-and-completeness-of-response",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Enhancing accuracy and completeness of response",
    showInMenu: true,
  },
  {
    displayText: "Asking about assessments, attitudes, values, motives, intentions etc.",
    id: "asking-about-assessments-attitudes-values-motives-intentions-etc",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Asking about assessments, attitudes, values, motives, intentions etc.",
    showInMenu: true,
  },
  {
    displayText: "Optimising response to knowledge questions",
    id: "optimising-response-to-knowledge-questions",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Optimising response to knowledge questions",
    showInMenu: true,
  },
  {
    displayText: "Obtaining valid and reliable measures of attitudes",
    id: "obtaining-valid-and-reliable-measures-of-attitudes",
    level: "h4",
    sourceTag: "p7",
    sourceText: "Obtaining valid and reliable measures of attitudes",
    showInMenu: true,
  },
  {
    displayText: "Question forms",
    id: "question-forms",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Question forms",
    showInMenu: true,
  },
  {
    displayText: "Question wording",
    id: "question-wording",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Question wording",
    showInMenu: true,
  },
  {
    displayText: "Question ordering",
    id: "question-ordering",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Question ordering",
    showInMenu: true,
  },
  {
    displayText: "Structure and layout of questionnaires",
    id: "structure-and-layout-of-questionnaires",
    level: "h2",
    sourceTag: "p7",
    sourceText: "6 Structure and layout of questionnaires",
    showInMenu: true,
  },
  {
    displayText: "Formatting questionnaires",
    id: "formatting-questionnaires",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Formatting questionnaires",
    showInMenu: true,
  },
  {
    displayText: "Aiding navigation through the questionnaire",
    id: "aiding-navigation-through-the-questionnaire",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Aiding ‘navigation’ through the questionnaire",
    showInMenu: true,
  },
  {
    displayText: "Choice of type-face and paper",
    id: "choice-of-type-face-and-paper",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Choice of type-face and paper",
    showInMenu: true,
  },
  {
    displayText: "Design principles for user-friendly questionnaires",
    id: "design-principles-for-user-friendly-questionnaires",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Design principles for user-friendly questionnaires",
    showInMenu: true,
  },
  {
    displayText: "Pre-testing and piloting questionnaires",
    id: "pre-testing-and-piloting-questionnaires",
    level: "h2",
    sourceTag: "p7",
    sourceText: "7 Pre-testing and piloting questionnaires",
    showInMenu: true,
  },
  {
    displayText: "Why pre-test and pilot questionnaires?",
    id: "why-pre-test-and-pilot-questionnaires",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Why pre-test and pilot questionnaires?",
    showInMenu: true,
  },
  {
    displayText: "Different types of pre-test and pilot",
    id: "different-types-of-pre-test-and-pilot",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Different types of pre-test and pilot",
    showInMenu: true,
  },
  {
    displayText: "Cognitive pre-testing",
    id: "cognitive-pre-testing",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Cognitive pre-testing",
    showInMenu: true,
  },
  {
    displayText: "Rehearsal pilots",
    id: "rehearsal-pilots",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Rehearsal pilots",
    showInMenu: true,
  },
  {
    displayText: "Maximising response rates",
    id: "maximising-response-rates",
    level: "h2",
    sourceTag: "li7",
    sourceText: "8 Maximising response rates",
    showInMenu: true,
  },
  {
    displayText: "Definition and analysis of unit and item response",
    id: "definition-and-analysis-of-unit-and-item-response",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Definition and analysis of unit and item response",
    showInMenu: true,
  },
  {
    displayText: "Reasons for unit non-response",
    id: "reasons-for-unit-non-response",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Reasons for unit non-response",
    showInMenu: true,
  },
  {
    displayText: "Compensating for unit non-response",
    id: "compensating-for-unit-non-response",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Compensating for unit non-response",
    showInMenu: true,
  },
  {
    displayText: "Survey management",
    id: "survey-management",
    level: "h2",
    sourceTag: "p7",
    sourceText: "9 SurvEy management",
    showInMenu: true,
  },
  {
    displayText: "Sampling for survey research",
    id: "sampling-for-survey-research",
    level: "h2",
    sourceTag: "li7",
    sourceText: "10 Sampling for survey research",
    showInMenu: true,
  },
  {
    displayText: "Why do we sample?",
    id: "why-do-we-sample",
    level: "h3",
    sourceTag: "p7",
    sourceText: "Why do we sample?",
    showInMenu: true,
  },
  {
    displayText: "Coding and data processing in survey research",
    id: "coding-and-data-processing-in-survey-research",
    level: "h2",
    sourceTag: "p7",
    sourceText: "11 CODING AND DATA PROCESSING IN SURVEY RESEARCH",
    showInMenu: true,
  },
  {
    displayText: "Conclusions",
    id: "conclusions",
    level: "h2",
    sourceTag: "p7",
    sourceText: "12 Conclusions",
    showInMenu: true,
  },
  {
    displayText: "Further reading",
    id: "further-reading",
    level: "h2",
    sourceTag: "p7",
    sourceText: "Further reading",
    showInMenu: true,
  },
  {
    displayText: "Digital-first questionnaire design",
    id: "digital-first-questionnaire-design",
    level: "h2",
    contentSource: "authored",
    showInMenu: true,
  },
  {
    displayText: "Mobile, SMS and app-based surveys",
    id: "mobile-sms-and-app-based-surveys",
    level: "h2",
    contentSource: "authored",
    showInMenu: true,
  },
  {
    displayText: "Social-platform recruitment and TikTok-era fieldwork",
    id: "social-platform-recruitment-and-tiktok-era-fieldwork",
    level: "h2",
    contentSource: "authored",
    showInMenu: true,
  },
  {
    displayText: "Data quality, bots and AI-generated responses",
    id: "data-quality-bots-and-ai-generated-responses",
    level: "h2",
    contentSource: "authored",
    showInMenu: true,
  },
  {
    displayText: "Accessibility, consent and privacy online",
    id: "accessibility-consent-and-privacy-online",
    level: "h2",
    contentSource: "authored",
    showInMenu: true,
  },
  {
    displayText: "Mixed-mode and adaptive fieldwork",
    id: "mixed-mode-and-adaptive-fieldwork",
    level: "h2",
    contentSource: "authored",
    showInMenu: true,
  },
];
